name: Build and Deploy Code

on:
  push:
    branches:
      - "main"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
      - uses: actions/checkout@v2
      - name: say hello
      - run: echo "Hello World"

